### ISSUE TITLE
Deploy live demo

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-auth0#1]
I deployed one here: https://datasette-auth0-demo-j7hipcg4aq-uc.a.run.app/

By running:

```
datasette publish cloudrun fixtures.db \
--install datasette-auth0 \
--plugin-secret datasette-auth0 domain "pillarpointstewards.us.auth0.com" \
--plugin-secret datasette-auth0 client_id "DLXBMPbtamC2STUyV7R6OFJFDsSTHqEA" \
--plugin-secret datasette-auth0 client_secret "..." \
--service datasette-auth0-demo
```
Still need to give it a nicer domain name and link to it from the README.

**Comment by simonw** [comment]
Setting this to `datasette-auth0-demo.datasette.io` - I added the CNAME in Vercel DNS, now setting that up in Cloud Run too.

**Comment by simonw** [comment]
I'm going to set this up to deploy on every push. Then I'll add it to the README and release a non-alpha 0.1.

**Comment by simonw** [comment]
Imitating https://github.com/simonw/datasette-json-html/blob/bb4c2ed9538745f866a781be8db04f70e0531cc8/.github/workflows/deploy-demo.yml

```yaml
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun demo.db \
          -m metadata.json \
          --install=https://github.com/simonw/datasette-json-html/archive/$GITHUB_SHA.zip \
          --service datasette-json-html-demo
```
